### ISSUE TITLE
bc is no longer installed by default in Pi-hole

### ISSUE THREAD

**Issue by chrisys** [jpmck/PADD#41] opened 2019-02-05 12:22 UTC
Not a bug report as such but more of a PSA: in [this](https://github.com/pi-hole/pi-hole/commit/3035fbf468dacc41762ec91015f5f15bea5c33fb#diff-689793e68cde6270d074695b71c969af) commit, Pi-hole removed the installation of `bc` by default. To run PADD now you'll need to manually install it. I've added it to the [balena Pi-hole](https://github.com/klutchell/balena-pihole/pull/3) project.

**Comment by jpmck** [comment] 2019-02-09 22:47
Thanks Chris. I'm in the process of removing the use of `bc` for the next release.

**Comment by jpmck** [comment] 2019-02-09 22:49
Duplicate of [Various "command not found' error messages continually displayed while running PADD.sh](https://github.com/jpmck/PADD/issues/42).

**Closed by jpmck** 2019-02-09 22:49 UTC
Labels: Bug Report, Duplicate Issue
